# Generated by Django 5.2.8 on 2025-11-29 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_remove_ticket_unique_row_seat_movie_session_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['created_at']},
        ),
    ]
