# Generated by Django 5.2.8 on 2025-11-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_alter_order_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_row_seat_movie_session',
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('row', 'seat', 'movie_session'), name='unique_row_seat_movie_session'),
        ),
    ]
