# Generated by Django 5.2.8 on 2025-11-29 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
